SocialWebsite/SocialWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("post.urls"), name="post"),
    path("", include("userdetail.urls"), name="userdetail"),
    path("messaging/", include("messaging.urls"), name="messaging"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/post/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "post"
urlpatterns = [
    path("", views.home, name="home"),
    path("create", views.create_post, name="create_post"),
    path("post/<slug:post_slug>", views.postdetail, name="post"),
    path("like/<slug:post_slug>", views.like, name="like"),
    path("comment/<slug:post_slug>", views.create_comment, name="create_comment"),
    path("profile/<str:username>", views.postdetail, name="your_profile"),
    path("user_post/<slug:post_slug>", views.your_post, name="your_post"),
    path("delete_post/<slug:post_slug>", views.delete_post, name="delete_post"),
    path("delete/<slug:post_slug>", views.delete, name="delete"),
    path(
        "share_email_form/<slug:post_slug>", views.share_form, name="share_email_form"
    ),
    path("", include("userdetail.urls"), name="userdetail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/userdetail/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "userdetail"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.logout_view, name="logout"),
    path("change", views.change_password, name="change"),
    path("profile", views.profile, name="profile"),
    path("user_profile/<str:username>", views.user_profile, name="user_profile"),
    path(
        "custom_profile/<str:username>",
        views.custom_profile,
        name="custom_search_profile",
    ),
    path("search", views.search_user, name="search_user"),
    path("follow/<str:username>", views.follow_user, name="follow_user"),
    path("edit_profile/<str:username>", views.edit_profile, name="edit"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/post/models.py
from django.db import models
from userdetail.models import Profile
from django.conf import settings
from django.utils.text import slugify
import uuid
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    slug = models.SlugField(null=False, unique=True)
    body = models.CharField(max_length=280, blank=True)
    image = models.ImageField(blank=True, upload_to="static/post_images")
    created = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(Profile, related_name="post_like", blank=True)

    def generate_slug(self):
        if self.body:
            slug = slugify(str(self.body[:10]) + "-" + str(self.id) + str(self.user))
        else:
            slug = slugify(f"post-{uuid.uuid4().hex[:8]}")
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}-{num}"
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_slug()
        super(Post, self).save(*args, **kwargs)

    def count_like(self):
        return self.likes.count()

    def get_username(self):
        return self.user

    def get_absolute_url(self):
        return reverse("post:your_post", args=[self.slug])

    def get_sharedpost_url(self):
        return reverse("post:post", args=[self.slug])

    def like_absolute_url(self, **kwargs):
        return reverse("post:your_post", kwargs={"slug": self.slug})

    def __str__(self):
        return f"{self.user} post created on  {self.created} ."


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, max_length="300", on_delete=models.CASCADE)
    body = models.CharField(max_length=200, blank=True)
    likes = models.ManyToManyField(Profile, related_name="comment_like", blank=True)

    def count_like(self):
        return self.likes.count()

    def get_username(self):
        return f"{self.user}"

    def __str__(self):
        return f"{self.body}"

SocialWebsite/post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["body", "image"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "body",
        ]


class ShareEmailForm(forms.Form):
    to = forms.EmailField()
    message = forms.CharField(required=False, widget=forms.Textarea)

SocialWebsite/post/views.py
from django.shortcuts import render
from userdetail.models import Profile
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, HttpResponse
from django.http import JsonResponse

from django.db.models import Count

from django.conf import settings
from django.contrib import messages

# for email
from django.core.mail import send_mail
from .forms import ShareEmailForm
from django.http import HttpRequest
from SocialWebsite.settings import EMAIL_HOST_USER


# Create your views here.
@login_required(login_url="userdetail:login")
def home(request):
    current_user = request.user
    try:
        user_profile = Profile.objects.get(user=current_user)
    except Profile.DoesNotExist:
        user_profile, created = Profile.objects.get_or_create(user=request.user)

    # Exclude posts created by the current user's profile
    posts = Post.objects.exclude(user=user_profile)

    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile, created = Profile.objects.get_or_create(user=request.user)

    # Fetching full model instances instead of values()
    profile_objects = Profile.objects.exclude(user=current_user)
    user_profile = User.objects.exclude(id=current_user.id)
    context = {
        "posts": posts,
        "profile": profile,
        "profile_objects": profile_objects,
        "user_profile": user_profile,
    }
    return render(request, "post/homepage.html", context)


# nav bar
def base(request):
    user = get_object_or_404(User, username=request.user)
    profile = Profile.objects.get(user=request.user)
    print(profile.profile_pic)
    return render(request, "base.html", {"profile": profile})


# creating post
@login_required
def create_post(request):
    if request.user.is_authenticated:
        profile = Profile.objects.get(
            user=request.user
        )  # Get the Profile of the logged-in user
        if request.method == "POST":
            post_form = PostForm(request.POST, request.FILES)
            if post_form.is_valid():
                post = post_form.save(commit=False)  # Don't save to the database yet
                post.user = profile  # Assign the Profile, not the User
                post.save()  # Now save the post
                messages.success(request, "Post created successfully!")
                return redirect("post:home")  # Redirect after successful post creation
            else:
                messages.error(request, "Error while posting form")
        else:
            post_form = PostForm()

    else:
        return redirect("post:home")
    return render(request, "post/create_post.html", {"post_form": post_form})


# post detail
def postdetail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    comments = Comment.objects.filter(post=post)
    comment_co = Comment.objects.annotate(Count("body")).filter(post=post)
    comment_count = len(comment_co)

    return render(
        request,
        "post/post.html",
        {"post": post, "comments": comments, "comment_count": comment_count},
    )


# post like
def like(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    msg = False
    if request.user.profile in post.likes.all():
        post.likes.remove(request.user.profile)
        msg = False

    else:
        post.likes.add(request.user.profile)
        msg = True

    like_count = post.count_like()
    referer = request.META.get(
        "HTTP_REFERER", "/"
    )  # referer is used to redirect to that same page
    return redirect(referer)


# Creating comment
@login_required
def create_comment(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = (
                request.user.profile
            )  # Assuming comments are linked to a user
            comment.save()
            return redirect("post:home")  # Redirect after successful comment
    else:
        form = CommentForm()
    return render(
        request, "post/create_comment.html", {"comment_form": form, "post": post}
    )


def your_post(request, id):
    user = request.user
    profile = get_object_or_404(Profile, user=user)  # Get the profile based on the user

    # Now filter posts using the profile (not the user)
    posts = Post.objects.filter(
        user=profile
    )  # Filter by profile since `user` is a ForeignKey to `Profile`
    comment = Comment.objects.get(post=post)
    return render(request, "post/your_post.html", {"posts": posts})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    print(post.user)
    print(f"requested user: {request.user}")
    if post.user.user == request.user:
        post.delete()
        return redirect("post:home")
    else:
        return HttpResponse(request, "Error")


def delete(request, post_slug):
    post = get_object_or_404(Post, id=post_slug)
    if post.user.user == request.user:
        return render(request, "post/delete_post.html", {"post": post})
    else:
        return HttpResponse(
            f"{request.user} Post user {post.user.user}You are not authorized to delete this post."
        )


@login_required
def share_form(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    sent = False
    form = ShareEmailForm()
    if request.method == "POST":
        form = ShareEmailForm(request.POST)
        if form.is_valid():
            post_url = request.build_absolute_uri(post.get_sharedpost_url())
            name = f"{request.user}"
            to = form.cleaned_data["to"]
            comment = form.cleaned_data["message"]
            message = (
                f"This post was shared by your friend {request.user.username}.\n\n"
                f"Post URL: {post_url}\n\n"
                f"Message: {comment}"
            )
            subject = "Social web app post share via email"
            send_mail(
                subject,
                message,
                EMAIL_HOST_USER,
                [to],
                fail_silently=False,  # Raise exceptions if email fails
            )

            referer = request.META.get(
                "HTTP_REFERER", "/"
            )  # referer is used to redirect to that same page
            return redirect(referer)
        success_message = "Email not sent"
    return render(
        request,
        "post/share_email_form.html",
        {
            "form": form,
            "post": post,
        },
    )

SocialWebsite/post/templates/base.html
{% load widget_tweaks %}
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    
    {% tailwind_css %}
</head>
<body class="font-roboto">
    <nav class="bg-white flex justify-center static font-sans">
        <div class="container w-full max-w-[810.545px] flex justify-between items-center h-16">
            <!-- Logo Section -->
            <div class="logo flex items-center">
                <img src="{% static "logo\webapp-logo.png" %}" alt="webapplogo" class="h-12 w-12">
            </div>     

            <!-- Home Link -->
            <div class="home">
                <a href="{% url 'post:home' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium"><img src="{% static 'logo\home-logo.png' %}" alt="Home Logo" class="h-10 w-10"></a>
            </div>

            <!-- Notification Link -->
            <div class="notification">
                <a href="#" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium"><img src="{% static 'logo\notification-logo.png' %}" alt="notification Logo" class="h-10 w-10"></a>
            </div>

            <!-- Create Post Link -->
            <div class="home">
                <a href="{% url 'post:create_post' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium"><img src="{% static 'logo\add-logo.png' %}" alt="add-post Logo" class="h-10 w-10"></a>
            </div>

            <!-- Logout Link -->
            {% if request.user.is_authenticated %}
            <div class="home">
                <a href="{% url 'userdetail:logout' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium"><img src="{% static 'logo\logout-logo.png' %}" alt="Logout logo" class="h-10 w-10"></a>
            </div>
            {% endif %}
            {% if request.user.is_authenticated %}
            <div class="home">
                <form action="{% url "userdetail:search_user" %}" method="GET">
                    <input type="text" name="q" placeholder="Search User"id="">
                </form>
                
            </div>
            {% endif %}

            <!-- Profile Section -->
            <div class="profile flex items-center">
                {% if request.user.is_authenticated %}
                    {% if profile.profile_pic %}
                        <a href="{% url 'userdetail:profile' %}">
                            <img class="h-10 w-10 rounded-full" src="{{ profile.profile_pic }}" alt="{{ request.user.username }}">
                        </a>
                    {% else %}
                        <a href="{% url 'userdetail:profile' %}">
                            <img class="h-10 w-10 rounded-full" src="{% static 'profile_images/default_profile.jpg' %}" alt="{{ request.user.username }}">
                        </a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'userdetail:login' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
</body>
</html>