SocialWebsite/SocialWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("post.urls"), name="post"),
    path("", include("userdetail.urls"), name="userdetail"),
    path("messaging/", include("messaging.urls"), name="messaging"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/post/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "post"
urlpatterns = [
    path("", views.home, name="home"),
    path("create", views.create_post, name="create_post"),
    path("post/<slug:post_slug>", views.postdetail, name="post"),
    path("like/<slug:post_slug>", views.like, name="like"),
    path("comment/<slug:post_slug>", views.create_comment, name="create_comment"),
    path("profile/<str:username>", views.postdetail, name="your_profile"),
    path("user_post/<slug:post_slug>", views.your_post, name="your_post"),
    path("delete_post/<slug:post_slug>", views.delete_post, name="delete_post"),
    path("delete/<slug:post_slug>", views.delete, name="delete"),
    path(
        "share_email_form/<slug:post_slug>", views.share_form, name="share_email_form"
    ),
    path("", include("userdetail.urls"), name="userdetail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/userdetail/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "userdetail"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.logout_view, name="logout"),
    path("change", views.change_password, name="change"),
    path("profile", views.profile, name="profile"),
    path("user_profile/<str:username>", views.user_profile, name="user_profile"),
    path(
        "custom_profile/<str:username>",
        views.custom_profile,
        name="custom_search_profile",
    ),
    path("search", views.search_user, name="search_user"),
    path("follow/<str:username>", views.follow_user, name="follow_user"),
    path("edit_profile/<str:username>", views.edit_profile, name="edit"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/post/models.py
from django.db import models
from userdetail.models import Profile
from django.conf import settings
from django.utils.text import slugify
import uuid
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    slug = models.SlugField(null=False, unique=True)
    body = models.CharField(max_length=280, blank=True)
    image = models.ImageField(blank=True, upload_to="static/post_images")
    created = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(Profile, related_name="post_like", blank=True)

    def generate_slug(self):
        if self.body:
            slug = slugify(str(self.body[:10]) + "-" + str(self.id) + str(self.user))
        else:
            slug = slugify(f"post-{uuid.uuid4().hex[:8]}")
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}-{num}"
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_slug()
        super(Post, self).save(*args, **kwargs)

    def count_like(self):
        return self.likes.count()

    def get_username(self):
        return self.user

    def get_absolute_url(self):
        return reverse("post:your_post", args=[self.slug])

    def get_sharedpost_url(self):
        return reverse("post:post", args=[self.slug])

    def like_absolute_url(self, **kwargs):
        return reverse("post:your_post", kwargs={"slug": self.slug})

    def __str__(self):
        return f"{self.user} post created on  {self.created} ."


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, max_length="300", on_delete=models.CASCADE)
    body = models.CharField(max_length=200, blank=True)
    likes = models.ManyToManyField(Profile, related_name="comment_like", blank=True)

    def count_like(self):
        return self.likes.count()

    def get_username(self):
        return f"{self.user}"

    def __str__(self):
        return f"{self.body}"

SocialWebsite/post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["body", "image"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "body",
        ]


class ShareEmailForm(forms.Form):
    to = forms.EmailField()
    message = forms.CharField(required=False, widget=forms.Textarea)

SocialWebsite/post/views.py
from django.shortcuts import render
from userdetail.models import Profile
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, HttpResponse
from django.http import JsonResponse

from django.db.models import Count

from django.conf import settings
from django.contrib import messages

# for email
from django.core.mail import send_mail
from .forms import ShareEmailForm
from django.http import HttpRequest
from SocialWebsite.settings import EMAIL_HOST_USER


# Create your views here.
@login_required(login_url="userdetail:login")
def home(request):
    current_user = request.user
    try:
        user_profile = Profile.objects.get(user=current_user)
    except Profile.DoesNotExist:
        user_profile, created = Profile.objects.get_or_create(user=request.user)

    # Exclude posts created by the current user's profile
    posts = Post.objects.exclude(user=user_profile)

    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile, created = Profile.objects.get_or_create(user=request.user)

    # Fetching full model instances instead of values()
    profile_objects = Profile.objects.exclude(user=current_user)
    user_profile = User.objects.exclude(id=current_user.id)
    context = {
        "posts": posts,
        "profile": profile,
        "profile_objects": profile_objects,
        "user_profile": user_profile,
    }
    return render(request, "post/homepage.html", context)


# nav bar
def base(request):
    user = get_object_or_404(User, username=request.user)
    profile = Profile.objects.get(user=request.user)
    print(profile.profile_pic)
    return render(request, "base.html", {"profile": profile})


# creating post
@login_required
def create_post(request):
    if request.user.is_authenticated:
        profile = Profile.objects.get(
            user=request.user
        )  # Get the Profile of the logged-in user
        if request.method == "POST":
            post_form = PostForm(request.POST, request.FILES)
            if post_form.is_valid():
                post = post_form.save(commit=False)  # Don't save to the database yet
                post.user = profile  # Assign the Profile, not the User
                post.save()  # Now save the post
                messages.success(request, "Post created successfully!")
                return redirect("post:home")  # Redirect after successful post creation
            else:
                messages.error(request, "Error while posting form")
        else:
            post_form = PostForm()

    else:
        return redirect("post:home")
    return render(request, "post/create_post.html", {"post_form": post_form})


# post detail
def postdetail(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    comments = Comment.objects.filter(post=post)
    comment_co = Comment.objects.annotate(Count("body")).filter(post=post)
    comment_count = len(comment_co)

    return render(
        request,
        "post/post.html",
        {"post": post, "comments": comments, "comment_count": comment_count},
    )


# post like
def like(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    msg = False
    if request.user.profile in post.likes.all():
        post.likes.remove(request.user.profile)
        msg = False

    else:
        post.likes.add(request.user.profile)
        msg = True

    like_count = post.count_like()
    referer = request.META.get(
        "HTTP_REFERER", "/"
    )  # referer is used to redirect to that same page
    return redirect(referer)


# Creating comment
@login_required
def create_comment(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = (
                request.user.profile
            )  # Assuming comments are linked to a user
            comment.save()
            return redirect("post:home")  # Redirect after successful comment
    else:
        form = CommentForm()
    return render(
        request, "post/create_comment.html", {"comment_form": form, "post": post}
    )


def your_post(request, id):
    user = request.user
    profile = get_object_or_404(Profile, user=user)  # Get the profile based on the user

    # Now filter posts using the profile (not the user)
    posts = Post.objects.filter(
        user=profile
    )  # Filter by profile since `user` is a ForeignKey to `Profile`
    comment = Comment.objects.get(post=post)
    return render(request, "post/your_post.html", {"posts": posts})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    print(post.user)
    print(f"requested user: {request.user}")
    if post.user.user == request.user:
        post.delete()
        return redirect("post:home")
    else:
        return HttpResponse(request, "Error")


def delete(request, post_slug):
    post = get_object_or_404(Post, id=post_slug)
    if post.user.user == request.user:
        return render(request, "post/delete_post.html", {"post": post})
    else:
        return HttpResponse(
            f"{request.user} Post user {post.user.user}You are not authorized to delete this post."
        )


@login_required
def share_form(request, post_slug):
    post = get_object_or_404(Post, slug=post_slug)
    sent = False
    form = ShareEmailForm()
    if request.method == "POST":
        form = ShareEmailForm(request.POST)
        if form.is_valid():
            post_url = request.build_absolute_uri(post.get_sharedpost_url())
            name = f"{request.user}"
            to = form.cleaned_data["to"]
            comment = form.cleaned_data["message"]
            message = (
                f"This post was shared by your friend {request.user.username}.\n\n"
                f"Post URL: {post_url}\n\n"
                f"Message: {comment}"
            )
            subject = "Social web app post share via email"
            send_mail(
                subject,
                message,
                EMAIL_HOST_USER,
                [to],
                fail_silently=False,  # Raise exceptions if email fails
            )

            referer = request.META.get(
                "HTTP_REFERER", "/"
            )  # referer is used to redirect to that same page
            return redirect(referer)
        success_message = "Email not sent"
    return render(
        request,
        "post/share_email_form.html",
        {
            "form": form,
            "post": post,
        },
    )

SocialWebsite/post/templates/post/create_comment.html
<form action="{% url "post:create_comment" post_slug=post.slug %}" method="POST">
    {% csrf_token %}
    {{comment_form.as_p}}
    <button type="submit">Submit</button>
</form>

SocialWebsite/post/templates/post/create_post.html
{% load static %}
{% include "base.html" %}
{% block content %}
<div class="flex justify-center w-full bg-gray-100 py-10">
    <div class="w-[600px] bg-white p-6 rounded-lg shadow-sm border border-gray-300">
        <h2 class="text-xl font-semibold text-gray-900 mb-4">Create a Post</h2>
        <form method="POST" enctype="multipart/form-data" class="space-y-4">
            {% csrf_token %}
            <div class="space-y-2">
                {{ post_form.as_p }}  <!-- Render form fields including the image field -->
            </div>
            
            <button type="submit" class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition duration-200">
                Submit
            </button>
        </form>
    </div>
</div>
{% endblock content %}

SocialWebsite/post/templates/post/delete_post.html
{% load static %}
{% include "base.html" %}
{{post.id}}
<form action="{% url "post:delete_post" post.id %}" >
    {% csrf_token %}
    <div class="flex flex-col">
        <button type="submit">Yes, delete it</button>
        <a href="{{post.get_absolute_url}}">No, go back</a>
    </div>
</form>

SocialWebsite/post/templates/post/homepage.html
{% load static %}
{% include "base.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src= 
    "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"> 
        </script>
</head>
<body >
    <div class="flex justify-center w-full">
    <div class=" felx justify-center w-[638.545px]   mt-11 pt-10  bg-blue-500 p-6 rounded-lg shadow-md ">
       
      
        <!-- Posted Items Section -->
        <div class="mt-0 space-y-6">
            {% for post in posts %}
            <div class="bg-white p-6 rounded-lg shadow-md border border-slate-rgb(0,0,0)">
                <div class="flex justify-between items-center mt-4 text-sm text-gray-600">
                    <!-- Profile Picture -->
                    {% if post.user.profile_pic %}
                    <img class="h-10 w-10 rounded-full" src="{{ post.user.profile_pic }}" alt="{{ post.user.username }}">
                    {% else %}
                    <img class="h-10 w-10 rounded-full" src="{% static 'profile_images/default_profile.jpg' %}" alt="{{ post.user.username }}">
                    {% endif %}
                    
                    <!-- Username and Post Details -->
                    <div class="flex flex-col ml-3">
                        <h2 class="font-semibold text-lg text-gray-800"><a href="{% url 'userdetail:user_profile' username=post.user.user %}" class="hover:underline">{{ post.user }}</h2>
                        <p class="text-sm text-gray-500">Posted by <a href="{% url 'userdetail:user_profile' username=post.user.user %}" class="hover:underline">{{ post.user }}</a> on {{ post.created | date }}</p>
                    </div>
                    <div class="flex flex-col">
                        <a href="{% url "post:post" post_slug=post.slug %}" class="text-blue-500 hover:underline">View Post</a>
                    </div>
                   
                </div>
        
                <!-- Post Content -->
                <p class="text-gray-700 ">{{ post.body }}</p>
                <!-- Post Image -->
                {% if post.image %}
                <img class="w-full mt-4 " src="{{ post.image.url }}" alt="{{ post.title }}">
                {% endif %}
       
                
               <!-- Actions: Like, Comment, Share -->
                <div class="mt-4 flex items-center space-x-6">
                    <!-- Like Button -->
                    <div class="flex items-center space-x-2">
                        {% if request.user.profile in post.likes.all %}
                        <a href="{% url 'post:like' post_slug=post.slug %}">
                            <img src="{% static 'logo/dislike-logo.png' %}" alt="Dislike" class="h-5 w-5">
                        </a>
                        {% else %}
                        <a href="{% url 'post:like' post_slug=post.slug %}">
                            <img src="{% static 'logo/like-logo.png' %}" alt="Like" class="h-5 w-5">
                        </a>
                        {% endif %}
                        <span class="text-gray-700 text-sm">({{ post.likes.count }})</span>
                    </div>

            <!-- Comment Button -->
            <div class="flex items-center space-x-2">
                <a href="{% url 'post:create_comment' post_slug=post.slug %}">
                    <img src="{% static 'logo/comment-logo.png' %}" alt="Comment" class="h-5 w-5">
                </a>
                <span class="text-gray-700 text-sm">{{ post.comment.count }}</span>
            </div>

            <!-- Share Button -->
            <div class="flex items-center">
                <a href="{% url 'post:share_email_form' post_slug=post.slug %}">
                    <img src="{% static 'logo/share-logo.png' %}" alt="Share" class="h-6 w-6">
                </a>
            </div>
        </div>

                
                {% comment %} <a href="{% url "post:create_comment" post_slug=post.slug %}"><img src="{% static "logo\comment-logo.png" %}" alt="webapplogo" class="h-12 w-12"></a>{{post.comment.count}}
                <a href="{% url "post:share_email_form" post_slug=post.slug %}"> <img src="{% static "logo\share-logo.png" %}" alt="webapplogo" class="h-12 w-12"></a> {% endcomment %}

            
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="felx justify-center h-1/2  min-w-1/3 mt-11 ml-11 pt-14  bg-blue-600 p-6 rounded-lg shadow-md" >
        <p>Suggested for you</p>
         
        <ul class="max-w-xs space-y-2">
            {% for user in user_profile %}
                <li class="flex items-center p-2 border-b border-gray-200 hover:bg-gray-100 transition duration-200">
                    
                    <a href="{% url 'userdetail:user_profile' username=user.username %}" class="flex-shrink-0">
                        {% if user.profile.profile_pic %}
                        <img class="h-12 w-12 rounded-full object-cover" src="{{ user.profile.profile_pic }}" alt="{{ user.username }}">
                        {% else %}
                        <img class="h-12 w-12 rounded-full object-cover" src="{% static 'profile_images/default_profile.jpg' %}" alt="Default Profile Picture">
                        {% endif %}
                    </a>
                        <div class="flex flex-col">
                            <span class="font-semibold text-gray-800">{{ user.username }}</span>
                            {% if user.bio %}
                                <span class="text-sm text-gray-600">{{ user.bio }}</span>
                            {% endif %}
                        </div>
                 
                </li>
            {% empty %}
                <li class="text-gray-500">No users found.</li>
            {% endfor %}
        </ul>  
    </div>
</div>
{% endblock content %}
</body>
</html>

SocialWebsite/post/templates/post/post.html
{% load static %}
{% load widget_tweaks %}
{% load static tailwind_tags %}
{% load tailwind_tags %}
{% include "base.html" %}
{% tailwind_css %}
<head>
    <title>Post</title>
</head>

<div class=" felx justify-center  max-w-md mt-11 pt-14  bg-blue-500 p-6 rounded-lg shadow-md ">
    <div class="bg-white p-6 rounded-lg shadow-md border border-slate-rgb(0,0,0)">
        <div class="flex items-center space-x-2 mb-4">
            <!-- Profile Picture -->
            {% if post.user.profile_pic %}
            <img class="h-10 w-10 rounded-full" src="{{ post.user.profile_pic }}" alt="{{ post.user.username }}">
            {% else %}
            <img class="h-10 w-10 rounded-full" src="{% static 'profile_images/default_profile.jpg' %}" alt="{{ post.user.username }}">
            {% endif %}
            <!-- Username and Post Details -->
            <div class="flex flex-col">
                <h2 class="font-semibold text-lg">{{ post.user }}</h2>
                <p class="text-sm text-gray-500">Posted by <a href="userdetail:profile">{{ post.user }}</a> on {{ post.created | date }}</p>
            </div>
        </div>

        <!-- Post Content -->
        <p class="container flex items-center justify-center text-gray-700 ">{{ post.body }}</p>
        {% if post.image %}
        <img class="w-full mt-4 " src="{{ post.image.url }}" alt="{{ post.title }}">
        {% endif %}
    
        <div class="contatiner flex items-center space-x-3 mt-4">
            {% if request.user.profile in post.likes.all %}  
            <a href="{% url 'post:like' post_slug=post.slug %}"><img src="{% static "logo\unlike-logo.png" %}" alt="webapplogo" class="h-12 w-12"> ({{ post.likes.count }})</a>
            {% else %}
            <a href="{% url 'post:like' post_slug=post.slug %}"> <img src="{% static "logo\like-logo.png" %}" alt="webapplogo" class="h-12 w-12"> ({{ post.likes.count }})</a>
            {% endif %}
            <a href="{% url "post:create_comment" post_slug=post.slug %}"><img src="{% static "logo\comment-logo.png" %}" alt="webapplogo" class="h-12 w-12"></a>
            <a href="#"><img src="{% static "logo\share-logo.png" %}" alt="webapplogo" class="h-12 w-12"></a>
        </div>
    </div>
    <a href="{% url "post:create_comment" post_slug=post.slug %}">Comment</a>
    <a href="{% url "post:share_email_form" post_slug=post.slug %}">Share</a>
    <p>likes: {{post.count_like}}</p>
</div>

<div class="comments-section">
<h2>Comments ({{ comment_count }})</h2>
{% for comment in comments %}
    <div class="comment">
        <strong>{{ comment.user.user.first_name }} {{comment.user.user.last_name}}</strong>:<!-- commentmodel-> user -> Profilemodel - > user - > username-->
        {{ comment.body }}<br>
        <small>Posted on {{ comment.created_at }}</small>
    </div>
            <hr>
        {% empty %}
            <p>No comments yet. Be the first to comment!</p>
        {% endfor %}
</div>

SocialWebsite/post/templates/post/share_email_form.html
{% load widget_tweaks %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email Share Form</title>

    {% tailwind_css %}
</head>
<body class="bg-gray-100 min-h-screen flex items-center justify-center">

    <!-- Form Container -->
    <div class="bg-white shadow-md rounded-lg p-6 max-w-lg w-full">
        <h1 class="text-2xl font-semibold text-center mb-6">Share Post via Email</h1>

        <form action="{% url 'post:share_email_form' post_slug=post.slug %}" method="POST" class="space-y-4">
            {% csrf_token %}
            
            <!-- Add borders to form fields -->
            <div>
                {{ form.to.label_tag }}
                {{ form.to|add_class:"border border-gray-300 rounded-md w-full px-3 py-2 focus:ring-blue-500 focus:border-blue-500" }}
            </div>

            <div>
                {{ form.message.label_tag }}
                {{ form.message|add_class:"border border-gray-300 rounded-md w-full px-3 py-2 focus:ring-blue-500 focus:border-blue-500" }}
            </div>

            <!-- Submit Button -->
            <div class="text-center">
                <input type="submit" value="Send" class="bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-md cursor-pointer">
            </div>
        </form>

        <!-- Success Message -->
        {% if sent %}
            <p class="text-green-600 text-center mt-4">Email sent successfully!</p>
        {% endif %}
    </div>

</body>
</html>

SocialWebsite/post/templates/post/your_post.html
{% load static %}
{% include "nav.html" %}
{% block content %}
<div class=" felx justify-center max-w-md mt-11 pt-14  bg-blue-500 p-6 rounded-lg shadow-md ">
    <div class="bg-white p-6 rounded-lg shadow-md border border-slate-rgb(0,0,0)">
    
        {% for post in posts %}

        <div class="flex items-center space-x-2 mb-4">
            <!-- Profile Picture -->
            {% if post.user.profile_pic %}
            <img class="h-10 w-10 rounded-full" src="{{ post.user.profile_pic.url }}" alt="{{ post.user.username }}">
            {% else %}
            <img class="h-10 w-10 rounded-full" src="{% static 'profile_images/default_profile.jpg' %}" alt="{{ post.user.username }}">
            {% endif %}

            <!-- Username and Post Details -->
            <div class="flex flex-col">
                <h2 class="font-semibold text-lg">{{ post.user }}</h2>
                <p class="text-sm text-gray-500">Posted by <a href="#">{{ post.user }}</a> on {{ post.created|date:"M d, Y" }}</p>
            </div>
            <div class="flex flex-col">
                <a href="{% url "post:delete" post.id %}">Delete</a>
            </div>
        </div>

        <!-- Post Content -->
        <p class="text-gray-700">{{ post.body }}</p>

        <!-- Post Image -->
        {% if post.image %}
        <img class="w-full mt-4" src="{{ post.image.url }}" alt="{{ post.title }}">
        {% endif %}

        <!-- Like, Comment, Share Buttons -->
        {% comment %} <div class="flex space-x-4 mt-2">
            <a href="post:" class="text-blue-500">Like</a>
            <a href="#" class="text-blue-500">Comment</a>
            <a href="#" class="text-blue-500">Share</a>
        </div> {% endcomment %}

        <p>Likes: {{ post.likes.count }}</p>

        <!-- Comments Section -->
        <div class="comments-section mt-4">
            <h2>Comments ({{ comments.count }})</h2>
            {% for comment in comments %}
            <div class="comment">
                <strong>{{ comment.user.user.first_name }} {{ comment.user.user.last_name }}</strong>: {{ comment.body }}<br>
                <small>Posted on {{ comment.created_at|date:"M d, Y H:i" }}</small>
            </div>
            <hr>
            {% empty %}
            <p>No comments yet. Be the first to comment!</p>
            {% endfor %}
        </div>

        <hr class="my-6">

        {% endfor %}

    </div>
</div>

{% endblock content %}