SocialWebsite/SocialWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("post.urls"), name="post"),
    path("", include("userdetail.urls"), name="userdetail"),
    path("messaging/", include("messaging.urls"), name="messaging"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/post/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "post"
urlpatterns = [
    path("", views.home, name="home"),
    path("create", views.create_post, name="create_post"),
    path("post/<slug:post_slug>", views.postdetail, name="post"),
    path("like/<slug:post_slug>", views.like, name="like"),
    path("comment/<slug:post_slug>", views.create_comment, name="create_comment"),
    path("profile/<str:username>", views.postdetail, name="your_profile"),
    path("user_post/<slug:post_slug>", views.your_post, name="your_post"),
    path("delete_post/<slug:post_slug>", views.delete_post, name="delete_post"),
    path("delete/<slug:post_slug>", views.delete, name="delete"),
    path(
        "share_email_form/<slug:post_slug>", views.share_form, name="share_email_form"
    ),
    path("", include("userdetail.urls"), name="userdetail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/userdetail/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "userdetail"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.logout_view, name="logout"),
    path("change", views.change_password, name="change"),
    path("profile", views.profile, name="profile"),
    path("user_profile/<str:username>", views.user_profile, name="user_profile"),
    path(
        "custom_profile/<str:username>",
        views.custom_profile,
        name="custom_search_profile",
    ),
    path("search", views.search_user, name="search_user"),
    path("follow/<str:username>", views.follow_user, name="follow_user"),
    path("edit_profile/<str:username>", views.edit_profile, name="edit"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/theme/templates/base_tailwind.html
{% load widget_tweaks %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% tailwind_css %}
</head>
<style>

    
</style>
<body >
    <nav class="bg-white shadow-lg  flex  justify-evenly static">
        <div class="container mx-auto px-4 flex justify-between items-center h-16">
            <!-- Logo Section -->
            <div class="logo flex items-center">
                <img src="" alt="web-app.JPG" class="h-10 w-10">
            </div>
            <div class="home">
                <a href="{% url 'post:home' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium">Home</a>
            </div>
            <div class="notification">
                <a href="#" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium">Notification</a>
            </div>
            <div class="home">
                <a href="{% url 'userdetail:change' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium">Change Password</a>
            </div>
            <div class="home">
                <a href="{% url 'userdetail:change' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium">{% if request.user.is_authenticated is True %}{{request.user.first_name}}{% endif %}</a>
            </div>
            <div class="home">
                <a href="{% url 'post:create_post' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium">Create Post</a>
            </div>
            {% if request.user.is_authenticated %}
            
            <div class="home">
                <a href="{% url 'userdetail:logout' %}" class="text-gray-700 hover:text-blue-500 px-3 py-2 rounded-md text-sm font-medium">Logout</a>
            </div>
            {% endif %}
            <!-- Profile Section -->
            <div class="profile flex items-center">
                {% if request.user.is_authenticated %}
                    {% if profile.profile_pic %}
                        <a href="{% url 'userdetail:profile' %}">
                            <img class="h-10 w-10 rounded-full" src="{{ profile.profile_pic }}" alt="{{ request.user.username }}">
                        </a>
        {% else %}
        <a href="{% url 'userdetail:profile' %}">
            <img class="h-10 w-10 rounded-full" src="static\profile_images\default_profile.jpg" alt="{{ request.user.username }}">
        </a>
    {% endif %}
{% else %}
    <a href="{% url 'userdetail:login' %}">Login</a>
    <p>hola</p>
{% endif %}
            </div>
        </div>
    </nav>
    
</html>