SocialWebsite/SocialWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("post.urls"), name="post"),
    path("", include("userdetail.urls"), name="userdetail"),
    path("messaging/", include("messaging.urls"), name="messaging"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/post/urls.py
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "post"
urlpatterns = [
    path("", views.home, name="home"),
    path("create", views.create_post, name="create_post"),
    path("post/<slug:post_slug>", views.postdetail, name="post"),
    path("like/<slug:post_slug>", views.like, name="like"),
    path("comment/<slug:post_slug>", views.create_comment, name="create_comment"),
    path("profile/<str:username>", views.postdetail, name="your_profile"),
    path("user_post/<slug:post_slug>", views.your_post, name="your_post"),
    path("delete_post/<slug:post_slug>", views.delete_post, name="delete_post"),
    path("delete/<slug:post_slug>", views.delete, name="delete"),
    path(
        "share_email_form/<slug:post_slug>", views.share_form, name="share_email_form"
    ),
    path("", include("userdetail.urls"), name="userdetail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/userdetail/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "userdetail"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("register", views.register, name="register"),
    path("logout", views.logout_view, name="logout"),
    path("change", views.change_password, name="change"),
    path("profile", views.profile, name="profile"),
    path("user_profile/<str:username>", views.user_profile, name="user_profile"),
    path(
        "custom_profile/<str:username>",
        views.custom_profile,
        name="custom_search_profile",
    ),
    path("search", views.search_user, name="search_user"),
    path("follow/<str:username>", views.follow_user, name="follow_user"),
    path("edit_profile/<str:username>", views.edit_profile, name="edit"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocialWebsite/userdetail/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    bio=models.CharField(max_length=100,blank=True,null=True)
    date_of_birth=models.DateField(blank=True,null=True)
    profile_pic=models.ImageField(blank=True,upload_to="static/profile_images")
    following = models.ManyToManyField(
    "self", 
    related_name="followed_by", 
    symmetrical=False, 
    blank=True,
)#This indicates a relationship between instances of the same model (i.e., a user can follow other users from the same model).
    
    def __str__(self) :
        return f"{self.user.first_name}"
    
    def follow(self, profile):
        if not self.is_following(profile):
            self.following.add(profile)

    def unfollow(self, profile):
        if self.is_following(profile):
            self.following.remove(profile)
    
    def count_following(self):
        return self.following.count()

    def count_followed_by(self):
        return self.followed_by.count()




    def get_absolute_url(self):
        return reverse("userdetail:user_profile", kwargs={"username": self.user.username})

    
    def is_following(self, profile):
        return self.following.filter(pk=profile.pk).exists()

SocialWebsite/userdetail/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    username.widget.attrs.update(
        {
            "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        }
    )
    password.widget.attrs.update(
        {
            "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
        }
    )


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        ]
        widgets = {
            "first_name": forms.TextInput(
                attrs={
                    "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500",
                    "placeholder": "Enter your first name",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500",
                    "placeholder": "Enter your last name",
                }
            ),
            "username": forms.TextInput(
                attrs={
                    "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500",
                    "placeholder": "Enter your username",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500",
                    "placeholder": "Enter your email",
                }
            ),
        }
        # explicitly defining password fields to override the custom the password field

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500",
                "placeholder": "Enter your password",
            }
        ),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(
            attrs={
                "class": "w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500",
                "placeholder": "Confirm your password",
            }
        ),
    )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password1"] != cd["password2"]:
            raise forms.ValidationError("The two password did not match.")
        return cd["password2"]


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "profile_pic",
            "date_of_birth",
            "bio",
        ]


class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username"]

SocialWebsite/userdetail/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .forms import LoginForm,RegisterForm,ProfileEditForm,UpdateUserForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from .models import Profile
from post.models import Post,Comment
from post.views import postdetail
from django.urls import reverse
# Create your views here.

def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            # Authenticate user with form data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)

            if user is not None and user.is_active:
                login(request, user)  # Only call login if user is valid
                return redirect("post:home")
            elif user is not None and not user.is_active:
                messages.error(request, "Account is inactive.")
            else:
            
                messages.error(request, "Invalid login credentials.")
                return render(request, "userdetail/login.html", {'form': form})
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = LoginForm()
    
    return render(request, "userdetail/login.html", {'form': form})
    
def logout_view(request):
    if request.user.is_authenticated:
        logout(request)  # This will log out the user
        messages.success(request, "You have been logged out.")  # Add a success message
    
    # Redirect to home or login page after logging out
    return render(request,'userdetail/logout.html')
    
def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username'].lower()
            password = form.cleaned_data['password2']
            email = form.cleaned_data['email']

            if User.objects.filter(email=email).exists():
                messages.error(request, "Email already exists. Please use another email.")
            else:
                user.set_password(password)
                user.save()

                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, "Registration successful!")
                    return redirect('post:home')
                else:
                    messages.error(request, "User authentication failed.")

    return render(request, 'userdetail/register.html', {"form": form})
    
@login_required(login_url='userdetail:login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important! Keeps the user logged in.
            messages.success(request, 'Your password was successfully updated!')
            return render(request,'userdetail/password_change_done.html')
        else:
            messages.error(request,'Invalid .')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'userdetail/password_change.html', {'form': form})
@login_required(login_url='userdetail:login')
def profile(request):
    profile=Profile.objects.get(user=request.user)
    current_user = request.user
    print(current_user)
    try:
        user_profile=Profile.objects.get(user=current_user)
    except Profile.DoesNotExist:
        user_profile,created = Profile.objects.get_or_create(user=request.user)

    # Exclude posts created by the current user's profile
    posts = Post.objects.filter(user=user_profile)
    
    posts_count=posts.count()
    print(posts_count)
    print(profile.count_following)
    return render(request,'userdetail/profile.html',{'profile':profile,
                                                     'posts':posts,
                                                     "posts_count":posts_count,
                                                     "followers":profile.count_following,
        "following":profile.count_followed_by,})
@login_required(login_url='userdetail:login')
def edit_profile(request, username):
    user = get_object_or_404(User, username=request.user.username)
    profile = get_object_or_404(Profile, user=request.user)
    if request.method == "POST":
        profile_form = ProfileEditForm(request.POST,request.FILES, instance=profile)
        user_form=UpdateUserForm(request.POST,instance=user)
        if profile_form.is_valid() and user_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,"Updated")
            return redirect('post:home')
        else:
            messages.error(request,"Error")
    else:
        profile_form = ProfileEditForm(instance=profile)
        user_form=UpdateUserForm(instance=user)

    return render(request, 'userdetail/profile_edit.html', {'profile_form': profile_form,'user_form':user_form})

def user_profile(request, username):
    try:
        user_profile = User.objects.get(username=username)
        profile = Profile.objects.get(user=user_profile)
    except (User.DoesNotExist, Profile.DoesNotExist):
        return render(request, 'userdetail/user_not_found.html')

    # Check if the logged-in user is following the current profile
    current_user_profile = Profile.objects.get(user=request.user)
    is_following = current_user_profile.is_following(profile)

    posts = Post.objects.filter(user=profile)
    posts_count = posts.count()

    context = {
        'user_profile': user_profile,
        'search_profile': user_profile,
        'profile': profile,
        'posts': posts,
        'posts_count': posts_count,
        'is_following': is_following,  # Pass the follow status dynamically
        'followers': profile.count_followed_by(),
        'following': profile.count_following(),
    }
    return render(request, 'userdetail/user_profile.html', context)

def follow_user(request, username): 
    user_to_follow = get_object_or_404(User, username=username)
    user_profile_to_follow = get_object_or_404(Profile, user=user_to_follow)
    current_user_profile = get_object_or_404(Profile, user=request.user)
    follow_user=True
    if current_user_profile.is_following(user_profile_to_follow):
        current_user_profile.unfollow(user_profile_to_follow)
        messages.success(request,"You have unfollowed")
        follow_user=False
        referer = request.META.get('HTTP_REFERER', '/')
        print(follow_user)
    else:
        current_user_profile.follow(user_profile_to_follow)
        messages.success(request,"You have followed")
        follow_user=True
        print(follow_user)
        referer = request.META.get('HTTP_REFERER', '/') # referer is used to redirect to that same page
    return redirect(referer)
    # return redirect(reverse(f"userdetail:user_profile",kwargs={"username":user_to_follow}))

#for searching custom user
def custom_profile(request,username):
    user_to_follow = get_object_or_404(User, username=username)
    user_profile_to_follow = get_object_or_404(Profile, user=user_to_follow)
    current_user_profile = get_object_or_404(Profile, user=request.user)
    context={'profile':current_user_profile}
    return render(request,'userdetail/user_profile.html',context)

def search_user(request):
    if request.method=='GET':
        q=request.GET.get('q')
        #__contains is equivalent to Select * where username==q
        users=User.objects.filter(username__icontains=q)
        return render(request,"userdetail/search.html",{'users':users})

SocialWebsite/userdetail/templates/userdetail/login.html
{% load tailwind_tags %}
{% load static %}
{%tailwind_css %}
<body>
    <div class="flex mt-0 pt-0 min-h-full flex-col justify-center px-6 py-2 lg:px-8">
        <div class="sm:mx-auto sm:w-full sm:max-w-sm">
           <div class="flex min-h-[180px] flex-col justify-center items-center px-6 py-4 lg:px-8">
    <img src="{% static 'logo/webapp-logo.png' %}" alt="webapplogo" class="h-32 w-32 object-contain">
</div>

          {% comment %} <img class="mx-auto h-10 w-auto" src="" alt="Name of socialwebapp"> {% endcomment %}
          <h2 class="mt-0 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Enter your Login Credentials</h2>
        </div>
        {% if messages %}
        {% for message in messages %}
            <h1 class="bg-red-400 flex justify-center mt-3 px-2 py-2">{{message}}</h1>
        
        {% endfor %}
        {% endif %}
    <div class="flex min-h-full flex-col justify-center px-6 py-2 lg:px-8">
        <div class="mt-0 sm:mx-auto sm:w-full sm:max-w-sm">
            <form action="{% url "userdetail:login" %}" method="POST">
            {% csrf_token %}
            <label for="username">Username</label>
            {{ form.username}}
            <label for="password">Password</label>
             {{form.password}} &nbsp;
             <input type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" value="Login">
        </form>
        </div>
        <div class="flex justify-center">
            <h1>Don't have an account? &nbsp;<a href="{% url "userdetail:register" %}" class="hover:underline text-blue-400">Register</a></h1>
        </div>
    </div>
</body>
</html>

SocialWebsite/userdetail/templates/userdetail/logout.html
{% include "nav.html" %}
<body>
    
        {% if messages %}
        {% for message in messages %}
            <h1 class="bg-red-400 flex justify-center mt-3 px-2 py-2">{{message}}</h1>
        
        {% endfor %}
        {% endif %}
        <div class="flex justify-center">
            <h1 class=" flex justify-center mt-3 px-2 py-2">You can &nbsp;
                <a href="{% url "userdetail:login" %}" class="hover:underline text-blue-400 ">Here</a>&nbsp; to log in again .</h1>
        </div>
</body>
</html>

SocialWebsite/userdetail/templates/userdetail/password_change_done.html
<p>Successful</p>

SocialWebsite/userdetail/templates/userdetail/profile.html
{% load static %}
{% include "base.html" %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{request.user.username}}</title>
</head>
{% block content %}
<body>
    <div class="max-w-md mx-auto text-center mt-10 space-y-4">

        <div>
            <img class="h-24 w-24 rounded-full object-cover mx-auto"
                 src="{% if profile.profile_pic %}{{ profile.profile_pic.url }}{% else %}{% static 'profile_images/default_profile.jpg' %}{% endif %}" 
                 alt="{{ profile.user }}">
        </div>
       
        
        <div>
            <h1 class="text-xl font-semibold">{{ profile.user.first_name }} {{ profile.user.last_name }}</h1>
            <p class="text-gray-500">@{{ profile.user.username }}</p>
            {% if profile.bio %}
            <p class="text-gray-600"> {{ profile.bio }}</p>
            {% endif %}
            {% if profile.date_of_birth  %}
            <p class="text-gray-600">Date of Birth: {{ profile.date_of_birth }}</p>
            {% endif %}
           
        </div>

        <div>
            <a href="{% url 'userdetail:edit' user.username %}" class="text-blue-500 font-medium border border-gray-300 py-1 px-4 rounded-full hover:bg-gray-100">
                Edit Profile
            </a>
        </div>

        <!-- Following and Followers Count -->
        <div class="flex justify-around text-center text-gray-700 border-t border-gray-200 pt-4">
            <div>
                <h2 class="font-semibold">Posts</h2>
                <p class="text-sm">{{ posts_count }}</p>
            </div>
            <div>
                <h2 class="font-semibold">Following</h2> 
                <p class="text-sm">{{ following }}</p>
            </div>
            <div>
                <h2 class="font-semibold">Followers</h2>
                <p class="text-sm">{{ followers }}</p>
            </div>
        </div>
        {% for post in posts  %}
        <h1>{{post.body}}</h1>
        <img src="{{post.image.url}}" alt="{{post.slug}}">
        {% if request.user.profile in post.likes.all %}  
    <a href="{% url 'post:like' post_slug=post.slug %}">Unlike<img src="{% static "logo\unlike-logo.jpeg" %}" alt="webapplogo" class="h-12 w-12"> ({{ post.likes.count }})</a>
    {% else %}
    <a href="{% url 'post:like' post_slug=post.slug %}">Like <img src="{% static "logo\like-logo.jpeg" %}" alt="webapplogo" class="h-12 w-12"> ({{ post.likes.count }})</a>
    {% endif %}
    <a href="{% url "post:create_comment" post_slug=post.slug %}">Comment</a>
    <a href="#">Share</a>
        {% endfor %}
    </div>
</body>

{% endblock content %}
</html>

SocialWebsite/userdetail/templates/userdetail/profile_edit.html
{% load static %}
{% load widget_tweaks %}
{% include "nav.html" %}

<!DOCTYPE html>
<html lang="en" class="h-full bg-gray-50">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Profile - Social Web App</title>
    <link href="{% static 'css/dist/styles.css' %}" rel="stylesheet">
</head>
<body class="h-full">
    <div class="flex min-h-full flex-col justify-center px-6 py-2 lg:px-8">
     {% if messages %}
        <div class="sm:mx-auto sm:w-full sm:max-w-sm mt-4">
            {% for message in messages %}
                <h1 class="bg-red-400 flex justify-center mt-3 px-2 py-2">{{ message }}</h1>
            {% endfor %}
        </div>
        {% endif %}
        <div class="max-w-md mx-auto mt-10">
            <h2 class="text-2xl font-bold mb-4">Update Profile</h2>
                    <form action="{% url 'userdetail:edit' user.username %}" method="POST" enctype="multipart/form-data" class="space-y-6">
                        {% csrf_token %}
                        <div class="mb-4">
                            <label for="{{ user_form.first_name.id_for_label }}" class="block text-gray-700 font-semibold mb-2">{{ user_form.first_name.label }}</label>
                            {{ user_form.first_name|add_class:"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ user_form.last_name.id_for_label }}" class="block text-gray-700 font-semibold mb-2">{{ user_form.last_name.label }}</label>
                            {{ user_form.last_name|add_class:"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ user_form.username.id_for_label }}" class="block text-gray-700 font-semibold mb-2">{{ user_form.username.label }}</label>
                            {{ user_form.username|add_class:"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ profile_form.profile_pic.id_for_label }}" class="block text-gray-700 font-semibold mb-2">{{ profile_form.profile_pic.label }}</label>
                            {{ profile_form.profile_pic|add_class:"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ profile_form.profile_pic.id_for_label }}" class="block text-gray-700 font-semibold mb-2">{{ profile_form.bio.label }}</label>
                            {{ profile_form.bio|add_class:"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
                        </div>
                        <div class="mb-4">
                            <label for="{{ profile_form.date_of_birth.id_for_label }}" class="block text-gray-700 font-semibold mb-2">{{ profile_form.date_of_birth.label }}</label>
                            {{ profile_form.date_of_birth|add_class:"w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" }}
                        </div>
                        <button type="submit" class="w-full py-2 px-4 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors">Update </button>
                    </form>
                </div>
    
            <div class="mt-6 flex justify-center">
                <p class="text-sm text-gray-600">Want to change your password? 
                    <a href="{% url 'userdetail:change' %}" class="font-medium text-indigo-600 hover:text-indigo-500">Change Password</a>
                </p>
            </div>
</body>
</html>

SocialWebsite/userdetail/templates/userdetail/user_not_found.html
{% include "nav.html" %}
<p>User not found . Go to <a href="post:home">Home</a></p>

SocialWebsite/userdetail/templates/userdetail/user_profile.html
{% load widget_tweaks %}
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile Page</title>
    
</head>
{% include "base.html" %}
{% block content %}
<body>
    <div class="max-w-md mx-auto text-center mt-10 space-y-6">
        <!-- Profile Picture -->
        <div class="flex flex-col items-center">
            <img class="h-24 w-24 rounded-full object-cover" 
                 src="{% if profile.profile_pic %}{{ profile.profile_pic.url }}{% else %}{% static 'profile_images/default_profile.jpg' %}{% endif %}" 
                 alt="{{ profile.user }}">
        </div>

        <!-- Name, Username, and Bio -->
        <div class="text-center">
            <h1 class="text-2xl font-bold">{{ profile.user.first_name }} {{ profile.user.last_name }}</h1>
            <p class="text-gray-500">@{{ profile.user.username }}</p>
            {% if profile.date_of_birth %}
            <p class="text-gray-600">Date of Birth: {{ profile.date_of_birth }}</p>
            {% endif %}
        </div>

        <!-- Messages -->
        <div>
            {% for message in messages %}
                <p class="text-sm text-red-500">{{ message }}</p>
            {% endfor %}
        </div>

        <!-- Follow/Unfollow Button -->
        <div>
        
                {% if is_following is True %}
                <a href="{% url 'userdetail:follow_user' username=profile.user.username %}" class="text-blue-500 font-medium border border-gray-300 py-1 px-4 rounded-full hover:bg-gray-100">
                    
                    Unfollow
                </a>
                {% else %}
                <a href="{% url 'userdetail:follow_user' username=profile.user.username %}" class="text-blue-500 font-medium border border-gray-300 py-1 px-4 rounded-full hover:bg-gray-100">
                    Follow
                </a>

                {% endif %}
                
            
                
            
        </div>

        <!-- Posts, Followers, Following Count -->
        <div class="flex justify-around text-center text-gray-700 border-t border-gray-200 pt-4">
            <div>
                <h2 class="font-semibold">Posts</h2>
                <p class="text-sm">{{ posts_count }}</p>
            </div>
            <div>
                <h2 class="font-semibold">Following</h2> 
                <p class="text-sm">{{ following }}</p>
            </div>
            <div>
                <h2 class="font-semibold">Followers</h2>
                <p class="text-sm">{{ followers }}</p>
            </div>
        </div>

        <!-- Posts Section -->
        <div class="space-y-6 mt-8">
            {% for post in posts %}
            <div class="flex items-center space-x-2 mb-4">
                <!-- Profile Picture -->
                {% if post.user.profile_pic %}
                <img class="mr-0 pr-0 h-10 w-10 rounded-full" src="{{ post.user.profile_pic }}" alt="{{ post.user.username }}">
                {% else %}
                <img class="mr-0 pr-0 h-10 w-10 rounded-full" src="{% static 'profile_images/default_profile.jpg' %}" alt="{{ post.user.username }}">
                {% endif %}
                
                <!-- Username and Post Details -->
                <div class="flex flex-col">
                    <h2 class="font-semibold mr-0 pr-0 h-10 w-10  text-lg">{{ post.user }}</h2>
                    
                    <p class="text-sm text-gray-500">Posted by <a href="userdetail:profile">{{ post.user }}</a> on {{ post.created | date }}</p>
                </div>
                
               
            </div>
               
            <div class="bg-white shadow-md rounded-lg p-6 ">
                <!-- Post Title or Content -->
                <h2 class="text-lg font-semibold">{{ post.title }}</h2>
                <p class="text-gray-700">{{ post.body }}</p>
                
                <!-- Post Image -->
                {% if post.image %}
                <img class="w-full object-cover mt-4 rounded-lg mr-0 pr-0 h-10 " src="{{ post.image.url }}" alt="{{ post.title }}">
                {% endif %}

                <!-- Like, Comment, Share -->
                <div class="flex justify-between items-center mt-4 text-sm text-gray-600">
                    <div class="flex space-x-4">
                       
                        {% if request.user.profile in post.likes.all %}
                
                        <a href="{% url 'post:like' post_slug=post.slug %}" class="hover:text-blue-500">Unlike<img src="{% static "logo\unlike-logo.jpeg" %}" alt="webapplogo" class="h-12 w-12"> ({{ post.likes.count }})</a>
                        {% else %}
                       
                        <a href="{% url 'post:like' post_slug=post.slug %}" class="hover:text-blue-500">Like <img src="{% static "logo\like-logo.jpeg" %}" alt="webapplogo" class="h-12 w-12"> ({{ post.likes.count }})</a>
                        {% endif %}
                        
                        
                        
                    
                        <a href="{% url 'post:create_comment' post_slug=post.slug %}" class="hover:text-blue-500">Comment</a>
                        <a href="#" class="hover:text-blue-500">Share</a>
                    </div>
                    
                </div>
            </div>

            <!-- Comments Section -->
            <div class="bg-gray-50 rounded-lg p-4 mt-4">
                
                {% for comment in comments %}
                <div class="mt-2">
                    <strong>{{ comment.user.user.first_name }} {{ comment.user.user.last_name }}</strong>: {{ comment.body }}<br>
                    <small class="text-gray-500">Posted on {{ comment.created_at }}</small> 
                    {% comment %} comment- issue {% endcomment %}
                </div>
               
                {% empty %}
                <p class="text-sm text-gray-500">No comments yet. Be the first to comment!</p>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</body>
{% endblock content %}
</html>